.TH pacaudit 1 "05 March 2017" "version 0.3"
.SH NAME
pacaudit
.SH SYNOPSIS
.B pacaudit [OPTION]
.SH DESCRIPTION
pacaudit checks installed packages against known vulnerabilities based on Arch CVE Monitoring Team data.

.SH FLAGS
pacaudit without flags prints the number of vulnerable packages installed.

.BR \-v\fR 
    run pacaudit in verbose mode. This prints the severity and all related CVE.

.BR \-n\fR 
    run pacaudit as nagios plugin. This prints OK, WARNING or CRITICAL.

.SH AUTHOR
Steffen Fritz <steffen@fritz.wtf>
